server:
  port: 8080
spring:        
  datasource: 
    initialization-mode: always
    url: "jdbc:mysql://localhost:3306/task"
    username: root
    password: root
  jpa: 
    hibernate: 
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQL5Dialect
    properties: 
      hibernate: 
        format_sql: true
        show_sql: true

